name: covoit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  
  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.0
  
  # State Management & Utilities
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  get_it: ^8.0.0
  uuid: ^4.5.1
  intl: ^0.19.0
  
  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true